### NumPy 
 NumPy is a Python library ,NumPy is used for working with arrays,NumPy is short for 'N umerical Python.

In [3]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))


[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [5]:
arr=np.array([1,2,3,4]),([1,2,3,4])
print(arr)

(array([1, 2, 3, 4]), [1, 2, 3, 4])


In [6]:
print(np.__version__)

1.21.5


# Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

# 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [7]:
import numpy as np
arr=np.array(12)
print(arr)

12


# 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [8]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


# 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.



In [11]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check Number of Dimensions
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [13]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


# Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [14]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [15]:
arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3])

7


# Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])


[2 3 4 5]


In [18]:
#Slice elements from index 4 to the end of the array:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


In [19]:
#Slice elements from the beginning to index 4 (not included):

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4])

[1 2 3 4]


In [20]:
#STEP
#Use the step value to determine the step of the slicing:
#Return every other element from index 1 to index 5:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])


[2 4]


# Data Types in Python
By default Python have these data types:

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j


In [21]:
#Get the data type of an array object

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [22]:
#Get the data type of an array containing strings.
arr= np.array(["apple","banana","cherry","orange"])
print(arr)

['apple' 'banana' 'cherry' 'orange']


In [24]:
#Create an array with data type string:
arr= np.array([1,2,3,4],dtype="S")
print(arr)
print(arr.dtype)
    

[b'1' b'2' b'3' b'4']
|S1


#For i, u, f, S and U we can define size as well.
arr= np.array([1,2,3,4],dtype="i")
print(arr)
print(arr.dtype)

In [28]:
arr= np.array([1,2,3,4],dtype="f")
print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


In [29]:
arr= np.array([1,2,3,4],dtype="U")
print(arr)
print(arr.dtype)

['1' '2' '3' '4']
<U1


# NumPy Array Copy vs View
## The Difference Between Copy and View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

In [30]:
arr=np.array([1,2,3,4,5,6])
x=arr.copy()
arr[0]=0
print(arr)
print(x)

[0 2 3 4 5 6]
[1 2 3 4 5 6]


In [32]:
#VIEW:
#Make a view, change the original array, and display both arrays
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 0

print(arr)
print(x)


[0 2 3 4 5]
[0 2 3 4 5]
